#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=36
#PBS -A lp_ees_swm_ls_001
#PBS -m abe
#PBS -M michel.bechtold@kuleuven.be
#PBS -o GRIB_log_000.txt
#PBS -e GRIB_err_000.txt

source /data/leuven/317/vsc31786/miniconda/bin/activate py3

cd /data/leuven/317/vsc31786/github/NU-WRF_Peatlands/Code/Postproc

nohup python read_GRIB2_2015_d02.py &> nohup_2015_d02.out &
nohup python read_GRIB2_2015_d03.py &> nohup_2015_d03.out &

wait
